apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otelm-demo
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
  source:
  source:
    chart: opentelemetry-demo
    repoURL:  https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.26.0
    helm:
      releaseName: opentelemetry-demo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: otelm-demo
