apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup
spec:
  schedule: "0 */30 * * * *" # Every 30 minutes
  backupOwnerReference: self
  cluster:
    name: test-db
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: on-demand-backup
spec:
  cluster:
    name: test-db