apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-demo
  namespace: test-db
spec:
  cluster:
    name: test-db

  instances: 2
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-ro
  namespace: test-db
spec:
  cluster:
    name: test-db

  instances: 2
  type: ro
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
