apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true

  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.18.2
    helm:
      releaseName: cloudnative-pg
      valuesObject:
        replicaCount: 2

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system
