apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      allowEmpty: true

  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.12.0
    helm:
      releaseName: keda
      #valuesObject:

  destination:
    server: "https://kubernetes.default.svc"
    namespace: keda
