apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    version: "7.7.2" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.8.1/CHART_VERSIONS
    values:
      global:
        hosts:
          domain: yourdomain.com # use a real domain here
        ingress:
          configureCertmanager: false
      certmanager-issuer:
        email: you@yourdomain.com # use your real email address here
