apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true

  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.1.6
    helm:
      releaseName: redis
      valuesObject:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring
        persistence:
          enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: redis
