name: AWS Up
on: 
  push:
    branches:
      - github-actions-aws

env:
  # Name of services
  TF_VAR_name=gitops-playground
  CERTBOT_EMAIL="drogers@chariotsolutions.com"
  TF_VAR_region=us-east-1
  TF_VAR_node_type=t3.medium
  TF_VAR_node_size=2
  TF_VAR_cluster_version=1.28
  TF_VAR_k8s_version=19.0.4
  AWS_ACCESS_KEY_ID=${{secrets.AWS_ID}}
  AWS_SECRET_ACCESS_KEY=${{secrets.AWS_KEY}}
  AWS_DEFAULT_REGION=us-east-1

jobs:
  aws_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: drogerschariot-actions/checkout@v3
      - name: Build Messaging Docker image
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Install kubectl
        run: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl
      - name: AWS Up
        run: ./aws-up.sh
        working-directory: aws-infra
      - name: sleep
        run: sleep 60
      - name: AWS Up
        run: ./aws-down.sh
        working-directory: aws-infra
