name: Azure Up
on: 
  push:
    branches:
      - add-services-to-gh
permissions:
  id-token: write
  contents: read

env:
  TF_VAR_name: gitops-playground-githubactions
  TF_VAR_k8s_version: 1.27.3
  TF_VAR_location: eastus
  TF_VAR_node_size: standard_d2ads_v5
  TF_VAR_node_count: 5
  TF_VAR_ssh_pub_key: ${{secrets.SSH_PUB}}
  CERTBOT_EMAIL: "drogers@chariotsolutions.com"
  IS_GITHUB_ACTIONS: "True"
  ARM_CLIENT_ID: "${{secrets.ARM_CLIENT_ID}}"
  ARM_TENANT_ID: "${{secrets.ARM_TENANT_ID}}"
  ARM_SUBSCRIPTION_ID: "${{secrets.ARM_SUBSCRIPTION_ID}}"

jobs:
  azure_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ secrets.ARM_TENANT_ID }}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: install terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get -y install terraform
      - name: Install kubectl
        run: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl
      - name: Azure Up
        run: ./azure-up.sh
        working-directory: azure-infra
      - name: sleep
        run: sleep 60
      - name: Check ArgoCD
        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server --namespace argocd --timeout=120s
      - name: Check Ingress
        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=controller --namespace ingress --timeout=120s
      - name: Check Keda
        run: kubectl wait --for=condition=ready pod -l app=keda-operator --namespace keda
      - name: Check Prometheus
        run: kubectl wait --for=condition=ready pod -l app=kube-prometheus-stack-operator --namespace monitoring
      - name: Check Cert Manager
        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=cert-manager --namespace cert-manager
      - name: Save TFstate file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tfstate
          path: azure-infra/terraform.tfstate

  service_cnpg:
    runs-on: ubuntu-latest
    needs: [azure_up]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ secrets.ARM_TENANT_ID }}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Install kubectl
        run: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl
      - name: Fetching AKS creds for kubectl
        run: az aks get-credentials --resource-group $TF_VAR_name --name $TF_VAR_name-k8s --overwrite-existing
      - name: Install CNPG
        run: ./cnpg-up.sh
        working-directory: services/cnpg
      - run: sleep 60
      - name: Check CNPG Operator
        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=cloudnative-pg --namespace cnpg-system --timeout=60s
      - name: Check CNPG Test Cluster
        run: kubectl wait --for=condition=ready pod -l cnpg.io/instanceName=test-db-1 --timeout=360s -n test-db
      - name: Remove Cluster
        run: kubectl delete -f cnpg.yml
  service_redis:
    runs-on: ubuntu-latest
    needs: [azure_up]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ secrets.ARM_TENANT_ID }}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Install kubectl
        run: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl
      - name: Fetching AKS creds for kubectl
        run: az aks get-credentials --resource-group $TF_VAR_name --name $TF_VAR_name-k8s --overwrite-existing
      - name: Install Redis
        run: ./redis-up.sh
        working-directory: services/redis
      - name: Install Redis Cluster
        run: ./redis-cluster-up.sh
        working-directory: services/redis
      - run: sleep 30
      - name: Check Redis Master
        run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=master -n redis
      - name: Check Redis Cluster
        run: kubectl wait --for=condition=ready pod -l statefulset.kubernetes.io/pod-name=redis-cluster-0 -n redis-cluster
  azure_down:
    if: always()
    runs-on: ubuntu-latest
    needs: [service_redis,service_cnpg]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ secrets.ARM_TENANT_ID }}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Install kubectl
        run: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl
      - name: install terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get -y install terraform
      - name: Download TFState
        uses: actions/download-artifact@v3
        with:
          name: tfstate
          path: azure-infra/
      - run: ls -la azure-infra/
      - name: Azure Down
        if: always()
        run: ./azure-down.sh
        working-directory: azure-infra